services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $receiverLocator: '@messenger.receiver_locator'
            $role: '%symfony_horizon.dashboard_role%'

    Saifulferoz\SymfonyHorizon\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../SymfonyHorizonBundle.php'

    Saifulferoz\SymfonyHorizon\Command\HorizonCommand:
        arguments:
            $config: '%symfony_horizon.config%'
        tags:
            - { name: 'console.command', command: 'messenger:horizon' }

    Saifulferoz\SymfonyHorizon\EventListener\MessengerEventListener:
        tags:
            - { name: 'kernel.event_subscriber' }

    Saifulferoz\SymfonyHorizon\Controller\DashboardController:
        public: true
        tags: ['controller.service_arguments']

    Saifulferoz\SymfonyHorizon\Controller\ApiController:
        public: true
        arguments:
            $config: '%symfony_horizon.config%'
        tags: ['controller.service_arguments']
